#include "http_client_cfg.h"

#define DEFAULT_RESEND_INTERVAL   5000 //milliseconds
#define DEFAULT_RESEND_QUEUE_MAX  10000
#define DEFAULT_RESEND_CONNECTION_LIMIT 10
#define DEFAULT_CONNECTION_LIMIT 10


extern int http_dest_header_func(cfg_t */*cfg*/, cfg_opt_t */*opt*/, int argc, const char **argv);

cfg_opt_t http_action_opt[]
{
    CFG_STR(PARAM_ACTION_NAME, "", CFGF_NODEFAULT),
    CFG_STR(PARAM_ACTION_ARGS_NAME, "", CFGF_NONE),
    CFG_END()
};

cfg_opt_t http_dest_opt[]
{
    CFG_STR(PARAM_AUTH_TYPE, "", CFGF_NODEFAULT),
    CFG_STR(PARAM_AUTH_PRIVATE_KEY, "", CFGF_NONE),
    CFG_STR(PARAM_AUTH_JWT_KIT, "", CFGF_NONE),
    CFG_STR(PARAM_AUTH_JWT_ISS, "", CFGF_NONE),
    CFG_STR(PARAM_AUTH_ACCESS_KEY, "", CFGF_NONE),
    CFG_STR(PARAM_AUTH_SECRET_KEY, "", CFGF_NONE),
    CFG_INT(PARAM_AUTH_TOKEN_LIFETIME, 3600, CFGF_NONE),

    CFG_STR(PARAM_MODE_NAME, "", CFGF_NODEFAULT),
    CFG_BOOL(PARAM_HTTP2_TLS, cfg_false, CFGF_NONE),
    CFG_FUNC(PARAM_HEADER, http_dest_header_func),
    CFG_STR(PARAM_AUTH_NAME, "", CFGF_NONE),
    CFG_STR(PARAM_AUTH_USRPWD, "", CFGF_NONE),
    CFG_STR(PARAM_CERT, "", CFGF_NONE),
    CFG_STR(PARAM_CERT_KEY, "", CFGF_NONE),
    CFG_STR_LIST(PARAM_URL_NAME, 0, CFGF_NODEFAULT),
    CFG_STR(PARAM_SOURCE_ADDRESS_NAME, "", CFGF_NONE),
    CFG_INT(PARAM_REQUEUE_LIMIT_NAME, 0, CFGF_NONE),
    CFG_STR_LIST(PARAM_SUCCESS_CODES_NAME, 0, CFGF_NODEFAULT),
    CFG_SEC(SECTION_ON_SUCCESS_NAME, http_action_opt, CFGF_NODEFAULT),
    CFG_SEC(SECTION_ON_FAIL_NAME, http_action_opt, CFGF_NODEFAULT),
    CFG_STR(PARAM_CONTENT_TYPE_NAME, "", CFGF_NODEFAULT),
    CFG_INT(PARAM_RESEND_QUEUE_MAX_NAME, DEFAULT_RESEND_QUEUE_MAX, CFGF_NONE),
    CFG_INT(PARAM_RESEND_CONNECTION_LIMIT_NAME, DEFAULT_RESEND_CONNECTION_LIMIT, CFGF_NODEFAULT),
    CFG_INT(PARAM_CONNECTION_LIMIT_NAME, DEFAULT_CONNECTION_LIMIT, CFGF_NODEFAULT),
    CFG_STR(PARAM_MIN_FILE_SIZE_NAME, "", CFGF_NODEFAULT),
    CFG_STR(PARAM_MAX_REPLY_SIZE_NAME, "", CFGF_NODEFAULT),
    CFG_END()
};

cfg_opt_t http_client_opt[] {
    CFG_SEC(SECTION_AUTH_NAME, http_dest_opt, CFGF_MULTI | CFGF_TITLE),
    CFG_SEC(SECTION_DEST_NAME, http_dest_opt, CFGF_MULTI | CFGF_TITLE),
    CFG_INT(PARAM_RESEND_INTERVAL_NAME, DEFAULT_RESEND_INTERVAL, CFGF_NONE),
    CFG_INT(PARAM_RESEND_QUEUE_MAX_NAME, DEFAULT_RESEND_QUEUE_MAX, CFGF_NONE),
    CFG_INT(PARAM_RESEND_CONNECTION_LIMIT_NAME, DEFAULT_RESEND_CONNECTION_LIMIT, CFGF_NONE),
    CFG_INT(PARAM_CONNECTION_LIMIT_NAME, DEFAULT_CONNECTION_LIMIT, CFGF_NONE),
    CFG_END()
};
