#include "http_client_cfg.h"

cfg_opt_t http_action_opt[]
{
    CFG_STR(PARAM_ACTION_VALUE_NAME, "", CFGF_NODEFAULT),
    CFG_STR(PARAM_ACTION_ARGS_NAME, "", CFGF_NONE),
    CFG_END()
};

cfg_opt_t http_dest_opt[]
{
    CFG_STR(PARAM_MODE_NAME, "", CFGF_NODEFAULT),
    CFG_STR_LIST(PARAM_URL_NAME, 0, CFGF_NODEFAULT),
    CFG_INT(PARAM_REQUEUE_LIMIT_NAME, 0, CFGF_NONE),
    CFG_STR_LIST(PARAM_SUCCESS_CODES_NAME, 0, CFGF_NODEFAULT),
    CFG_SEC(SECTION_ACTION_NAME, http_action_opt, CFGF_MULTI | CFGF_TITLE),
    CFG_STR(PARAM_CONTENT_TYPE_NAME, "", CFGF_NODEFAULT),
    CFG_END()
};

cfg_opt_t http_client_opt[] {
    CFG_SEC(SECTION_DIST_NAME, http_dest_opt, CFGF_MULTI | CFGF_TITLE),
    CFG_INT(PARAM_RESEND_INTERVAL_NAME, DEFAULT_RESEND_INTERVAL, CFGF_NONE),
    CFG_INT(PARAM_RESEND_QUEUE_MAX_NAME, DEFAULT_RESEND_QUEUE_MAX, CFGF_NONE),
    CFG_END()
};
