.TH "cfg_value_t" 3 "Sun Aug 19 2018" "Version 3.2.2" "confuse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cfg_value_t \- Data structure holding the value of a fundamental option value\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <confuse\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "long int \fBnumber\fP"
.br
.RI "integer value "
.ti -1c
.RI "double \fBfpnumber\fP"
.br
.RI "floating point value "
.ti -1c
.RI "\fBcfg_bool_t\fP \fBboolean\fP"
.br
.RI "boolean value "
.ti -1c
.RI "char * \fBstring\fP"
.br
.RI "string value "
.ti -1c
.RI "\fBcfg_t\fP * \fBsection\fP"
.br
.RI "section value "
.ti -1c
.RI "void * \fBptr\fP"
.br
.RI "user-defined value "
.in -1c
.SH "Detailed Description"
.PP 
Data structure holding the value of a fundamental option value\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for confuse from the source code\&.
