
streams {
  iface = lo
  src_hosts = { 127.0.0.0 }
  dst_hosts = { 127.0.0.0 }
  src_ports = { 5000 }
  dst_ports = { 6000 }
}

#streams {
#  iface = lo
#  src_hosts = { ::1 }
#  dst_hosts = { ::1 }
#  src_ports = { 5000 }
#  dst_ports = { 6000-6001 }
#}
