usr/include/sems
core/*.h usr/include/sems/
core/*.cc usr/include/sems/
core/sip/*.h usr/include/sems/sip/
core/resample/*.h usr/include/sems/resample/
core/ampi usr/include/sems/
core/amci usr/include/sems/
core/rtcp usr/include/sems/
core/compat/*.h usr/include/sems/compat/
core/compat/*.c usr/include/sems/compat/
unit_tests/*.h usr/include/sems/unit_tests/
core/rtp usr/include/sems/
usr/lib/pkgconfig usr/lib/
usr/share/cmake/sems usr/share/cmake/
apps/redis/unit_tests/*.h usr/include/sems/apps/redis/unit_tests
