MESSAGE(STATUS "Enable building of the bundled Spandsp")

set (SPANDSP_DIR third/spandsp)
set (SPANDSP_SRC_DIR ${PROJECT_SOURCE_DIR}/${SPANDSP_DIR})
set (SPANDSP_BIN_DIR ${PROJECT_BINARY_DIR}/${SPANDSP_DIR})
set (SPANDSP_BUNDLED_PREFIX ${SPANDSP_BIN_DIR}/src/.libs)
set (SPANDSP_BUNDLED_LIB ${SPANDSP_BUNDLED_PREFIX}/libspandsp.a)

set(SPANDSP_CONFIG_ARGS --enable-static --with-pic)

add_custom_target(libspandsp ALL DEPENDS ${SPANDSP_BUNDLED_LIB})

file(MAKE_DIRECTORY ${SPANDSP_BIN_DIR})
add_custom_command(OUTPUT ${SPANDSP_BUNDLED_LIB}
    PRE_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy_directory ${SPANDSP_SRC_DIR} ${SPANDSP_BIN_DIR}
    COMMAND ./configure ${SPANDSP_CONFIG_ARGS}
    COMMAND $(MAKE)
    WORKING_DIRECTORY ${SPANDSP_BIN_DIR})

set(SPANDSP_BUNDLED_INCLUDE_DIRS ${SPANDSP_BIN_DIR}/src)

add_library(SPANDSP_bundled STATIC IMPORTED)
set_property(TARGET SPANDSP_bundled PROPERTY IMPORTED_LOCATION ${SPANDSP_BUNDLED_LIB})
set(SPANDSP_BUNDLED_LIBS -L/lib64 -ltiff -lm ${SPANDSP_BUNDLED_LIB})

install(FILES ${SPANDSP_BIN_DIR}/src/spandsp.h DESTINATION /usr/include/sems)
install(DIRECTORY ${SPANDSP_BIN_DIR}/src/spandsp DESTINATION /usr/include/sems
        FILES_MATCHING PATTERN "*.h")
